config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :fighters
  resources :events, shallow: true do
    resources :fights
  end
  resources :fights, shallow: true do
    resources :forecasts, only: %i[create update destroy]
  end
end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  validates_presence_of :first_name, :last_name
  enum sport_kind: %i[boxing mma]

  scope :search, ->(query) {
    where 'first_name ILIKE :q OR last_name ILIKE :q OR alias ILIKE :q', q: "%#{query || ''}%"
  }

  # def self.search(query)
  #   # fighters = Fighter.all
  #
  #   # if query.present?
  #   #
  #   # end
  #
  #   # fighters
  # end

  def name
    [first_name, last_name].compact.join(' ')
  end

  def presentation
    [first_name, "\"#{self.alias}\"", last_name].compact.join(' ')
  end

end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  def index
    @fighters = Fighter.search(params[:query])
  end

  def show
  end

  def new
    @fighter = Fighter.new
    respond_to do |format|
      format.html
      format.js { render 'show_form' }
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js { render 'show_form' }
    end
  end

  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # def create
  #   @fighter = Fighter.new(fighter_params)
  #
  #   respond_to do |format|
  #     if @fighter.save
  #       format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
  #       format.js
  #     else
  #       format.html { render :new }
  #       format.js { render :new }
  #     end
  #   end
  # end

  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: 'Fighter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_fighter
    @fighter = Fighter.find(params[:id])
  end

  def fighter_params
    params.require(:fighter).permit(:first_name, :last_name, :alias, :sport_kind)
  end
end

app/views/fighters/_form.html.slim
= simple_form_for @fighter do |f|
  = hidden_field_tag 'fighter[sport_kind]', 'mma'
  /= f.input :sport_kind
  = f.input :last_name
  = f.input :first_name
  = f.input :alias
  = f.button :submit

app/views/fighters/_modal_form.html.slim
= simple_form_for @fighter, remote: true do |f|
  .modal-header
    = close_modal_button
    h4.modal-title = t("fighters.#{@fighter.new_record? ? 'new' : 'edit'}.title")
  .modal-body
    = hidden_field_tag 'fighter[sport_kind]', 'mma'
    /= f.input :sport_kind
    = f.input :last_name
    = f.input :first_name
    = f.input :alias
  .modal-footer
    = f.button :submit

app/views/fighters/create.js.erb
App.Fighters.modalSelect('<%= @fighter.as_json(only: :id, methods: :name).to_json.html_safe %>');

app/views/fighters/edit.html.slim
h3
  = link_to icon('chevron-left'), fighters_path
  =< t '.title'
== render 'form'

app/views/fighters/index.html.slim
h3
  = t '.title'
  small =< link_to t('fighters.new.title'), new_fighter_path

table.table.table-hover
  thead
    tr
      th = Fighter.human_attribute_name(:sport_kind)
      th = Fighter.human_attribute_name(:last_name)
      th = Fighter.human_attribute_name(:first_name)
      th = Fighter.human_attribute_name(:alias)
      th

  tbody
    - @fighters.each do |fighter|
      tr
        td = fighter.sport_kind
        td = fighter.last_name
        td = fighter.first_name
        td = fighter.alias
        td: .btn-group.btn-group-xs
          = link_to icon(:edit), edit_fighter_path(fighter), class: 'btn btn-default'
          = link_to icon(:trash), fighter, data: {confirm: t('helpers.confirmation')}, method: :delete, class: 'btn btn-danger'

app/views/fighters/new.html.slim
h3
  = link_to icon('chevron-left'), fighters_path
  =< t '.title'
== render 'form'

app/views/fighters/show.html.slim
p#notice = notice

p
  strong First name:
  = @fighter.first_name
p
  strong Last name:
  = @fighter.last_name
p
  strong Alias:
  = @fighter.alias
p
  strong Sport kind:
  = @fighter.sport_kind

= link_to 'Edit', edit_fighter_path(@fighter)
'|
= link_to 'Back', fighters_path

app/views/fighters/show_form.js.erb
<% content_for(:modal_content, render('modal_form')) %>
App.showModal('<%= j render('shared/modal') %>', 'sm');

app/views/fighters/update.js.erb
App.Fighters.modalSelect('<%= @fighter.as_json(only: :id, methods: :name).to_json.html_safe %>');