config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :fighters
  resources :events, shallow: true do
    resources :fights
  end
  resources :fights, shallow: true do
    resources :forecasts, only: %i[create update destroy]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :fights
  has_many :forecasts, through: :fights
  validates_presence_of :name, :time, :kind
  enum kind: %i[boxing mma]
  enum status: %i[active finished]

  def upcoming?
    time > Time.current
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update destroy]
  decorates_assigned :events, :event, :forecasts

  def index
    @events = Event.all
  end

  def show
    @event = Event.includes(fights: :forecasts).find(params[:id])
    set_forecasts
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params.merge(author_id: current_user.id))

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_forecasts
    @forecasts = @event.fights.collect do |fight|
      fight.forecasts.by(current_user).first_or_initialize
    end
  end

  def event_params
    params.require(:event).permit(:name, :time, :description, :kind)
  end

end

app/helpers/event_helper.rb
module EventHelper

  def event_kind_collection_for_select
    Event.kinds.keys.map { |type| [Event.human_attribute_name("type.#{type}"), type] }
  end

end

app/views/events/_fight.html.slim
li.fight.list-group-item data-id=fight.id
  = fight.fighter_tag 1
  '  vs.
  = fight.fighter_tag 2

app/views/events/_forecast.html.slim
li.fight.list-group-item data-id=forecast.id
  - if forecast.upcoming?
    = simple_form_for forecast, url: fight_forecasts_path(forecast.fight), remote: true, html: {class: 'forecast-form form-inline'} do |f|
      = f.association :winner, as: :radio_buttons, collection: fighters_collection(forecast.fight), label: false
      = f.input :way, collection: win_ways_collection, label: false
      = f.submit class: 'btn'
  - else
    = forecast.fighter_tag 1
    '  vs.
    = forecast.fighter_tag 2

  span.pull-right = forecast.link_to_remove

app/views/events/_form.html.slim
= simple_form_for @event, html: {class: 'form'} do |f|
  = hidden_field_tag 'event[kind]', 'mma'
  /= f.input :kind, collection: event_kind_collection_for_select, prompt: false
  = f.input :name
  = f.input :time, with_css_classes: true, start_year: Time.now.year, end_year: Time.now.year.next
  = f.input :description
  = f.button :submit

app/views/events/edit.html.slim
h3
  = link_to icon('chevron-left'), events_path
  =< t '.title'

== render 'form'

= link_to 'Show', @event

app/views/events/index.html.slim
h3
  = t '.title'
  small =< link_to t('events.new.title'), new_event_path

table.table.table-hover
  thead
    tr
      th = Event.human_attribute_name(:name)
      th = Event.human_attribute_name(:date)
      th = Event.human_attribute_name(:kind)
      th

  tbody
    - events.each do |event|
      tr
        td = link_to event.name, event.object
        td = event.date
        td = event.kind
        td: .btn-group.btn-group-xs
          = link_to icon(:edit), edit_event_path(event), class: 'btn btn-default'
          = link_to icon(:trash), event, data: {confirm: t('helpers.confirmation')}, method: :delete, class: 'btn btn-danger'

app/views/events/new.html.slim
h3
  = link_to icon('chevron-left'), events_path
  =< t '.title'
== render 'form'

app/views/events/show.html.slim
h3
  =< link_to icon('chevron-left'), events_path
  =< "[#{event.kind}]"
  =< event.name
  small =< event.datetime

= event.description

#fights-container.panel.panel-default
  .panel-heading: h4.panel-title = t 'fights.index.title'
  ul#fights.list-group
    - if user_signed_in?
      = render collection: forecasts, partial: 'events/forecast'
    - else
      = render collection: event.fights, partial: 'events/fight'
#new-fight-form-container
= link_to t('fights.new.title'), new_event_fight_path(@event), class: 'btn btn-default btn-sm', remote: true
hr
= link_to t('helpers.links.edit'), edit_event_path(@event), class: 'btn btn-default'